#!/bin/sh
########################################################################
# Begin sysstat
#
# Description : Clear kernel counters for sysstat
#
########################################################################

### BEGIN INIT INFO
# Provides: sysstat
# Required-Start: $local_fs
# Should-Start: sysctl console
# Required-Stop:
# Should-Stop:
# Default-Start: S
# Default-Stop:
# Short-Description:   Reset system activity data collector file
# Description:         Reset system activity data collector file
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
	start)	log_info_msg "Calling the system activity data collector (sadc)..."
		/usr/lib/sa/sadc -F -L -
		evaluate_retval
	;;
	*)	echo "Usage: ${0} start"
		exit 1
	;;
esac
# End /etc/init.d/sysstat
